"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory\
$git_branch\
$git_status\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
$docker_context\
$conda\
$cmd_duration\
$line_break\
$character"""

palette = "kanagawa_wave"

[directory]
style = "bold crystalBlue"
format = "[$path]($style) "
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
format = "[$branch]($style)"
symbol = ""
style = "bold oniViolet"

[git_status]
format = "[$all_status$ahead_behind]($style) "
style = "waveRed"
modified = "*"
staged = "+"
untracked = "?"
deleted = "x"

[c]
format = "[c $version]($style) "
style = "surimiOrange"
version_format = "${major}.${minor}"

[rust]
format = "[rs $version]($style) "
style = "waveRed"
version_format = "${major}.${minor}"

[golang]
format = "[go $version]($style) "
style = "springBlue"
version_format = "${major}.${minor}"

[nodejs]
format = "[node $version]($style) "
style = "springGreen"
version_format = "${major}.${minor}"

[php]
format = "[php $version]($style) "
style = "oniViolet"
version_format = "${major}.${minor}"

[java]
format = "[java $version]($style) "
style = "waveRed"
version_format = "${major}.${minor}"

[kotlin]
format = "[kt $version]($style) "
style = "oniViolet"
version_format = "${major}.${minor}"

[haskell]
format = "[hs $version]($style) "
style = "oniViolet"
version_format = "${major}.${minor}"

[python]
format = "[py $version]($style) "
style = "carpYellow"
version_format = "${major}.${minor}"

[docker_context]
format = "[docker $context]($style) "
style = "springBlue"

[conda]
format = "[conda $environment]($style) "
style = "springGreen"
ignore_base = false

[cmd_duration]
show_milliseconds = true
format = "[$duration]($style) "
style = "fujiGray"
disabled = false
show_notifications = true
min_time_to_notify = 45000

[line_break]
disabled = false

[character]
success_symbol = "[❯](bold springGreen)"
error_symbol = "[❯](bold waveRed)"
vimcmd_symbol = "[❮](bold springGreen)"
vimcmd_replace_one_symbol = "[❮](bold oniViolet)"
vimcmd_replace_symbol = "[❮](bold oniViolet)"
vimcmd_visual_symbol = "[❮](bold carpYellow)"

[palettes.kanagawa_wave]
sumiInk1 = "#1F1F28"
fujiWhite = "#DCD7BA"
crystalBlue = "#7E9CD8"
oniViolet = "#957FB8"
springGreen = "#98BB6C"
springBlue = "#7FB4CA"
carpYellow = "#E6C384"
surimiOrange = "#FFA066"
waveRed = "#E46876"
fujiGray = "#727169"
