"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory\
$git_branch\
$git_status\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
$docker_context\
$conda\
$cmd_duration\
$line_break\
$character"""

palette = "kanagawa_wave"

[directory]
style = "bold crystal_blue"
format = "[󰉋 $path]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
format = " [·](fuji_gray) [󰘬 $branch]($style)"
symbol = ""
style = "bold oni_violet"

[git_status]
format = "$all_status$ahead_behind"
conflicted = "[ =${count}](bold wave_red)"
ahead = "[ ⇡${count}](spring_blue)"
behind = "[ ⇣${count}](spring_blue)"
diverged = "[ ⇕⇡${ahead_count}⇣${behind_count}](oni_violet)"
untracked = "[ ?${count}](carp_yellow)"
stashed = '[ \$${count}](oni_violet)'
modified = "[ *${count}](wave_red)"
staged = "[ +${count}](spring_green)"
renamed = "[ »${count}](surimi_orange)"
deleted = "[ x${count}](wave_red)"
up_to_date = ""

[c]
format = " [·](fuji_gray) [ $version]($style)"
style = "spring_green"
version_format = "${major}.${minor}"

[rust]
format = " [·](fuji_gray) [ $version]($style)"
style = "surimi_orange"
version_format = "${major}.${minor}"

[golang]
format = " [·](fuji_gray) [ $version]($style)"
style = "spring_blue"
version_format = "${major}.${minor}"

[nodejs]
format = " [·](fuji_gray) [ $version]($style)"
style = "spring_blue"
version_format = "${major}.${minor}"

[php]
format = " [·](fuji_gray) [ $version]($style)"
style = "spring_green"
version_format = "${major}.${minor}"

[java]
format = " [·](fuji_gray) [ $version]($style)"
style = "surimi_orange"
version_format = "${major}.${minor}"

[kotlin]
format = " [·](fuji_gray) [ $version]($style)"
style = "spring_green"
version_format = "${major}.${minor}"

[haskell]
format = " [·](fuji_gray) [ $version]($style)"
style = "spring_green"
version_format = "${major}.${minor}"

[python]
format = " [·](fuji_gray) [ $version]($style)"
style = "carp_yellow"
version_format = "${major}.${minor}"

[docker_context]
format = " [·](fuji_gray) [ $context]($style)"
style = "spring_blue"

[conda]
format = " [·](fuji_gray) [ $environment]($style)"
style = "spring_green"
ignore_base = false

[cmd_duration]
show_milliseconds = true
format = " [·](fuji_gray) [󱎫 $duration]($style)"
style = "fuji_gray"
disabled = false
show_notifications = true
min_time_to_notify = 45000

[line_break]
disabled = false

[character]
success_symbol = "[❯](bold spring_green)"
error_symbol = "[❯](bold wave_red)"
vimcmd_symbol = "[❮](bold spring_green)"
vimcmd_replace_one_symbol = "[❮](bold oni_violet)"
vimcmd_replace_symbol = "[❮](bold oni_violet)"
vimcmd_visual_symbol = "[❮](bold carp_yellow)"

[palettes.kanagawa_wave]
sumi_ink_1 = "#1F1F28"
fuji_white = "#DCD7BA"
crystal_blue = "#7E9CD8"
oni_violet = "#957FB8"
spring_green = "#98BB6C"
spring_blue = "#7FB4CA"
carp_yellow = "#E6C384"
surimi_orange = "#FFA066"
wave_red = "#E46876"
fuji_gray = "#727169"
