-- Local generated module; see README.md machine-specific config.
require("monitors")
-- hl.config({ autogenerated = true }) -- remove this line to remove the warning
-- This is an example Hyprland Lua config file.
-- Refer to the wiki for more information.
-- https://wiki.hypr.land/Configuring/Start/
------------------
---- MONITORS ----
------------------
hl.monitor({
    output = "DP-2",
    mode = "3840x2160@165",
    position = "0x0",
    scale = 1.5,
    vrr = 0,
    transform = 0,
})

hl.monitor({
    output = "DP-1",
    mode = "3840x2160@60",
    position = "2560x-50",
    scale = 1.5,
    transform = 0,
})

hl.monitor({
    output = "HDMI-A-1",
    mode = "3840x2160@119.88",
    position = "4000x214",
    scale = 1,
    transform = 0,
})

-- MOVE TO MONITOR DP-2
hl.bind("SUPER + SHIFT + 3",
    hl.dsp.window.move({
        monitor = "HDMI-A-1",
        follow = true
    })
)
-- MOVE TO MONITOR HDMI-A-1
hl.bind("SUPER + SHIFT + 3",
    hl.dsp.window.move({
        monitor = "HDMI-A-1",
        follow = true
    })
)

---------------------
---- MY PROGRAMS ----
---------------------
local terminal = "ghostty"
local fileManager = "dolphin"

-------------------
---- AUTOSTART ----
-------------------
hl.on("hyprland.start", function()
    hl.exec_cmd("/usr/lib/polkit-kde-authentication-agent-1")
    hl.exec_cmd("noctalia")
end)

-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------
hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")

-----------------------
----- PERMISSIONS -----
-----------------------
hl.permission("/usr/(bin|local/bin)/grim", "screencopy", "allow")
hl.permission("/usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland", "screencopy", "allow")

-----------------------
---- LOOK AND FEEL ----
-----------------------
hl.config({
    general = {
        gaps_in = 5,
        gaps_out = 20,
        border_size = 2,
        col = {
            active_border = {
                colors = {
                    "rgba(cba6f7ee)",
                    "rgba(89b4faee)",
                },
                angle = 45,
            },
            inactive_border = "rgba(45475aaa)",
        },
        resize_on_border = false,
        allow_tearing = false,
        layout = "dwindle",
    },
    misc = {
        vrr = 0,
    },
    decoration = {
        rounding = 10,
        rounding_power = 2,
        active_opacity = 1.0,
        inactive_opacity = 0.96,
        shadow = {
            enabled = true,
            range = 5,
            render_power = 3,
            color = 0xcc11111b,
        },
        blur = {
            enabled = true,
            size = 4,
            passes = 2,
            vibrancy = 0.15,
        },
    },
    animations = {
        enabled = true,
    },
})
--------------------
---- ANIMATIONS ----
--------------------
hl.curve("easeOutQuint", {
    type = "bezier",
    points = {
        { 0.23, 1 },
        { 0.32, 1 },
    },
})

hl.curve("easeInOutCubic", {
    type = "bezier",
    points = {
        { 0.65, 0.05 },
        { 0.36, 1 },
    },
})

hl.curve("linear", {
    type = "bezier",
    points = {
        { 0, 0 },
        { 1, 1 },
    },
})

hl.curve("almostLinear", {
    type = "bezier",
    points = {
        { 0.5, 0.5 },
        { 0.75, 1 },
    },
})

hl.curve("quick", {
    type = "bezier",
    points = {
        { 0.15, 0 },
        { 0.1, 1 },
    },
})

hl.curve("easy", {
    type = "spring",
    mass = 1,
    stiffness = 238.1191,
    dampening = 24.21279333,
})

hl.animation({
    leaf = "global",
    enabled = true,
    speed = 10,
    bezier = "default",
})

hl.animation({
    leaf = "border",
    enabled = true,
    speed = 5.39,
    bezier = "easeOutQuint",
})

hl.animation({
    leaf = "windows",
    enabled = true,
    speed = 4.79,
    spring = "easy",
})

hl.animation({
    leaf = "windowsIn",
    enabled = true,
    speed = 4.1,
    spring = "easy",
    style = "popin 87%",
})

hl.animation({
    leaf = "windowsOut",
    enabled = true,
    speed = 1.49,
    bezier = "linear",
    style = "popin 87%",
})

hl.animation({
    leaf = "fadeIn",
    enabled = true,
    speed = 1.73,
    bezier = "almostLinear",
})

hl.animation({
    leaf = "fadeOut",
    enabled = true,
    speed = 1.46,
    bezier = "almostLinear",
})

hl.animation({
    leaf = "fade",
    enabled = true,
    speed = 3.03,
    bezier = "quick",
})

hl.animation({
    leaf = "layers",
    enabled = true,
    speed = 3.81,
    bezier = "easeOutQuint",
})

hl.animation({
    leaf = "layersIn",
    enabled = true,
    speed = 4,
    bezier = "easeOutQuint",
    style = "fade",
})

hl.animation({
    leaf = "layersOut",
    enabled = true,
    speed = 1.5,
    bezier = "linear",
    style = "fade",
})

hl.animation({
    leaf = "fadeLayersIn",
    enabled = true,
    speed = 1.79,
    bezier = "almostLinear",
})

hl.animation({
    leaf = "fadeLayersOut",
    enabled = true,
    speed = 1.39,
    bezier = "almostLinear",
})

hl.animation({
    leaf = "workspaces",
    enabled = true,
    speed = 1.94,
    bezier = "almostLinear",
    style = "fade",
})

hl.animation({
    leaf = "workspacesIn",
    enabled = true,
    speed = 1.21,
    bezier = "almostLinear",
    style = "fade",
})

hl.animation({
    leaf = "workspacesOut",
    enabled = true,
    speed = 1.94,
    bezier = "almostLinear",
    style = "fade",
})

hl.animation({
    leaf = "zoomFactor",
    enabled = true,
    speed = 7,
    bezier = "quick",
})
-----------------
---- LAYOUTS ----
-----------------
hl.config({
    dwindle = {
        preserve_split = true,
    },
})

hl.config({
    master = {
        new_status = "master",
    },
})

hl.config({
    scrolling = {
        fullscreen_on_one_column = true,
    },
})
----------------
----  MISC  ----
----------------
hl.config({
    misc = {
        force_default_wallpaper = -1,
        disable_hyprland_logo = false,
    },
})

hl.config({
    xwayland = {
        force_zero_scaling = true,
    },
})

---------------
---- INPUT ----
---------------
hl.config({
    input = {
        kb_layout = "eu",
        kb_variant = "",
        kb_model = "",
        kb_options = "",
        kb_rules = "",
        follow_mouse = 1,
        sensitivity = 0,
        touchpad = {
            natural_scroll = false,
        },
    },
})

hl.gesture({
    fingers = 3,
    direction = "horizontal",
    action = "workspace",
})
---------------------
---- KEYBINDINGS ----
---------------------
local mainMod = "SUPER"
local sharedMod = "CTRL + ALT"
---------------------
-- APPS / NOCTALIA
---------------------
local ipc = "noctalia msg "

-- Terminal
hl.bind(mainMod .. " + Q", hl.dsp.exec_cmd(terminal))
hl.bind(sharedMod .. " + RETURN", hl.dsp.exec_cmd(terminal))

-- File manager
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(fileManager))

-- Noctalia launcher
hl.bind(mainMod .. " + R", hl.dsp.exec_cmd(ipc .. "panel-toggle launcher"))

-- Sidebar/notifications equivalent
hl.bind(mainMod .. " + B", hl.dsp.exec_cmd(ipc .. "panel-toggle control-center notifications"))

-- Dashboard equivalent
hl.bind(mainMod .. " + D", hl.dsp.exec_cmd(ipc .. "panel-toggle control-center"))

-- Noctalia settings
hl.bind(mainMod .. " + comma", hl.dsp.exec_cmd(ipc .. "settings-toggle"))

-- Session / power menu
hl.bind(mainMod .. " + X", hl.dsp.exec_cmd(ipc .. "panel-toggle session"))

-- Lock
hl.bind(mainMod .. " + L", hl.dsp.exec_cmd(ipc .. "session lock"))

-- Wallpaper picker
hl.bind(mainMod .. " + W", hl.dsp.exec_cmd(ipc .. "panel-toggle wallpaper"))

---------------------
-- WINDOWS
---------------------
-- Close active window

hl.bind(mainMod .. " + C", hl.dsp.window.close())
hl.bind(sharedMod .. " + SHIFT + Q", hl.dsp.window.close())

-- Toggle floating

hl.bind(
    mainMod .. " + V",
    hl.dsp.window.float({
        action = "toggle",
    })
)
hl.bind(
    sharedMod .. " + SHIFT + SPACE",
    hl.dsp.window.float({
        action = "toggle",
    })
)

-- Fullscreen
hl.bind(mainMod .. " + F", hl.dsp.window.fullscreen())
hl.bind(sharedMod .. " + F", hl.dsp.window.fullscreen())

-- Pseudo tiling
hl.bind(mainMod .. " + P", hl.dsp.window.pseudo())

-- Toggle dwindle split
hl.bind(mainMod .. " + J", hl.dsp.layout("togglesplit"))

-- Center floating window
hl.bind(mainMod .. " + SHIFT + C", hl.dsp.window.center())
---------------------
-- WINDOW SWITCHER
---------------------
hl.bind("ALT + TAB", hl.dsp.exec_cmd(ipc .. "window-switcher"))
---------------------
-- FOCUS
---------------------
hl.bind(
    mainMod .. " + left",
    hl.dsp.focus({
        direction = "left",
    })
)

hl.bind(
    mainMod .. " + right",
    hl.dsp.focus({
        direction = "right",
    })
)

hl.bind(
    mainMod .. " + up",
    hl.dsp.focus({
        direction = "up",
    })
)

hl.bind(
    mainMod .. " + down",
    hl.dsp.focus({
        direction = "down",
    })
)

local sharedDirections = {
    h = "left",
    j = "down",
    k = "up",
    l = "right",
    left = "left",
    down = "down",
    up = "up",
    right = "right",
}

for key, direction in pairs(sharedDirections) do
    hl.bind(
        sharedMod .. " + " .. key,
        hl.dsp.focus({
            direction = direction,
        })
    )
end
---------------------
-- MOVE WINDOWS
---------------------
hl.bind(
    mainMod .. " + SHIFT + left",
    hl.dsp.window.move({
        direction = "left",
    })
)

hl.bind(
    mainMod .. " + SHIFT + right",
    hl.dsp.window.move({
        direction = "right",
    })
)

hl.bind(
    mainMod .. " + SHIFT + up",
    hl.dsp.window.move({
        direction = "up",
    })
)

hl.bind(
    mainMod .. " + SHIFT + down",
    hl.dsp.window.move({
        direction = "down",
    })
)

for key, direction in pairs(sharedDirections) do
    hl.bind(
        sharedMod .. " + SHIFT + " .. key,
        hl.dsp.window.move({
            direction = direction,
        })
    )
end

---------------------
-- WORKSPACES
---------------------
for i = 1, 10 do
    local key = i % 10
    hl.bind(
        mainMod .. " + " .. key,
        hl.dsp.focus({
            workspace = i,
        })
    )

    hl.bind(
        mainMod .. " + SHIFT + " .. key,
        hl.dsp.window.move({
            workspace = i,
        })
    )

    if i <= 9 then
        hl.bind(
            sharedMod .. " + " .. key,
            hl.dsp.focus({
                workspace = i,
            })
        )

        hl.bind(
            sharedMod .. " + SHIFT + " .. key,
            hl.dsp.window.move({
                workspace = i,
            })
        )
    end
end

---------------------
-- MAGIC WORKSPACE
---------------------
hl.bind(mainMod .. " + S", hl.dsp.workspace.toggle_special("magic"))

hl.bind(
    mainMod .. " + SHIFT + S",
    hl.dsp.window.move({
        workspace = "special:magic",
    })
)

---------------------
-- WORKSPACE SCROLL
---------------------
hl.bind(
    mainMod .. " + mouse_down",
    hl.dsp.focus({
        workspace = "e+1",
    })
)

hl.bind(
    mainMod .. " + mouse_up",
    hl.dsp.focus({
        workspace = "e-1",
    })
)

---------------------
-- MOUSE
---------------------
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(), {
    mouse = true,
})

hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), {
    mouse = true,
})

---------------------
-- SCREENSHOT
---------------------
-- Keep known-working screenshot flow
hl.bind(mainMod .. " + SHIFT + A", hl.dsp.exec_cmd("bash -lc 'grim -g \"$(slurp)\" - | wl-copy'"))

---------------------
-- CLIPBOARD
---------------------
hl.bind(mainMod .. " + SHIFT + V", hl.dsp.exec_cmd(ipc .. "panel-toggle clipboard"))

---------------------
-- NIGHT LIGHT
---------------------
hl.bind(mainMod .. " + N", hl.dsp.exec_cmd(ipc .. "nightlight-force-toggle"))

---------------------
-- NOTIFICATIONS
---------------------
hl.bind(mainMod .. " + SHIFT + B", hl.dsp.exec_cmd(ipc .. "notification-clear-active"))

---------------------
-- LOGOUT
---------------------
hl.bind(mainMod .. " + SHIFT + M", hl.dsp.exec_cmd(ipc .. "session logout"))

---------------------
-- AUDIO
---------------------
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd(ipc .. "volume-up"), {
    locked = true,
    repeating = true,
})

hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd(ipc .. "volume-down"), {
    locked = true,
    repeating = true,
})

hl.bind("XF86AudioMute", hl.dsp.exec_cmd(ipc .. "volume-mute"), {
    locked = true,
})

hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd(ipc .. "mic-mute"), {
    locked = true,
})

---------------------
-- BRIGHTNESS
---------------------
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd(ipc .. "brightness-up"), {
    locked = true,
    repeating = true,
})

hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd(ipc .. "brightness-down"), {
    locked = true,
    repeating = true,
})
---------------------
-- MEDIA
---------------------
hl.bind("XF86AudioNext", hl.dsp.exec_cmd(ipc .. "media next"), {
    locked = true,
})

hl.bind("XF86AudioPause", hl.dsp.exec_cmd(ipc .. "media toggle"), {
    locked = true,
})

hl.bind("XF86AudioPlay", hl.dsp.exec_cmd(ipc .. "media toggle"), {
    locked = true,
})

hl.bind("XF86AudioPrev", hl.dsp.exec_cmd(ipc .. "media previous"), {
    locked = true,
})

--------------------------------
---- NOCTALIA INTEGRATION ----
--------------------------------
-- Float the native Noctalia settings window.
hl.window_rule({
    name = "noctalia-settings",
    match = {
        class = "dev.noctalia.Noctalia",
    },
    float = true,
    size = { 1080, 920 },
})

-- Blur Noctalia surfaces in Hyprland and let Noctalia animate them itself.
hl.layer_rule({
    name = "noctalia",
    match = {
        namespace = "^noctalia-(bar-.+|notification|dock|panel|attached-panel|osd|window-switcher)$",
    },
    no_anim = true,
    ignore_alpha = 0.5,
    blur = true,
    blur_popups = true,
})

--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------
local suppressMaximizeRule = hl.window_rule({
    name = "suppress-maximize-events",
    match = {
        class = ".*",
    },
    suppress_event = "maximize",
})

---------------------
-- XWAYLAND FIX
---------------------
hl.window_rule({
    name = "fix-xwayland-drags",
    match = {
        class = "^$",
        title = "^$",
        xwayland = true,
        float = true,
        fullscreen = false,
        pin = false,
    },
    no_focus = true,
})

---------------------
-- HYPRLAND RUN
---------------------
hl.window_rule({
    name = "move-hyprland-run",
    match = {
        class = "hyprland-run",
    },
    move = "20 monitor_h-120",
    float = true,
})

---------------------
-- GUILD WARS 2
---------------------
hl.window_rule({
    name = "gw2-monitor",
    match = {
        class = "steam_app_1284210",
    },
    monitor = "DP-2",
})

hl.window_rule({
    name = "steam-games-idle-inhibit",
    match = {
        class = "^steam_app_.*$",
    },
    idle_inhibit = "fullscreen",
})


-- For Noctalia Color templates
-- Local generated module; see README.md machine-specific config.
require("noctalia").apply_theme()
